spring:
  application:
    name: UberBookingService
  datasource:
    url: jdbc:mysql://localhost:3306/Uber_Db_Local
    username: root
    password: #Rajat26
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate


server:
  port: 8001

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true





